---
- name: Verify Rancher Deployment
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if Docker is running
      ansible.builtin.service_facts:

    - name: Assert Docker service is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].state == 'running'
        success_msg: "✓ Docker is running"
        fail_msg: "✗ Docker is not running"

    - name: Get Rancher container info
      community.docker.docker_container_info:
        name: rancher
      register: rancher_container

    - name: Assert Rancher container is running
      ansible.builtin.assert:
        that:
          - rancher_container.exists
          - rancher_container.container.State.Status == 'running'
        success_msg: "✓ Rancher container is running"
        fail_msg: "✗ Rancher container is not running"

    - name: Check Rancher API
      ansible.builtin.uri:
        url: "https://localhost:8443/ping"
        validate_certs: false
        status_code: 200
      register: rancher_api
      until: rancher_api.status == 200
      retries: 60
      delay: 10

    - name: Get private network IP
      ansible.builtin.set_fact:
        rancher_access_ip: "{{ rancher_public_ip | default(ansible_all_ipv4_addresses | select('match', '^192\\.168\\.') | first) }}"

    - name: Display success message
      ansible.builtin.debug:
        msg:
          - "======================================================="
          - "✓✓✓ ALL TESTS PASSED! ✓✓✓"
          - "======================================================="
          - "✓ Docker installed and running"
          - "✓ Rancher container deployed"
          - "✓ Rancher API responding"
          - ""
          - "Access Rancher from your browser:"
          - "  https://{{ rancher_access_ip }}:8443"
          - ""
          - "Login credentials:"
          - "  Username: admin"
          - "  Password: {{ rancher_bootstrap_password }}"
          - ""
          - "Note: Accept the self-signed certificate"
          - "======================================================="
