---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Include role defaults
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Include role tasks
      ansible.builtin.import_tasks:
        file: ../../tasks/main.yml
