---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false
      failed_when: docker_version.rc != 0

    - name: Display Docker version
      ansible.builtin.debug:
        var: docker_version.stdout

    - name: Check if Docker service is running
      ansible.builtin.service_facts:

    - name: Assert Docker service is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].state == 'running'
        fail_msg: "Docker service is not running"
        success_msg: "Docker service is running"

    - name: Check if Rancher data volume exists
      community.docker.docker_volume_info:
        name: rancher_data
      register: rancher_volume

    - name: Assert Rancher volume exists
      ansible.builtin.assert:
        that:
          - rancher_volume.exists
        fail_msg: "Rancher data volume does not exist"
        success_msg: "Rancher data volume exists"

    - name: Get Rancher container info
      community.docker.docker_container_info:
        name: rancher
      register: rancher_container

    - name: Assert Rancher container exists and is running
      ansible.builtin.assert:
        that:
          - rancher_container.exists
          - rancher_container.container.State.Status == 'running'
        fail_msg: "Rancher container is not running properly"
        success_msg: "Rancher container is running"

    - name: Verify Rancher ports are exposed
      ansible.builtin.assert:
        that:
          - rancher_container.container.NetworkSettings.Ports['80/tcp'] is defined
          - rancher_container.container.NetworkSettings.Ports['443/tcp'] is defined
        fail_msg: "Rancher ports are not properly exposed"
        success_msg: "Rancher ports are properly exposed"

    - name: Check Rancher API (may take some time - K3s initialization)
      ansible.builtin.uri:
        url: "https://localhost:8443/ping"
        validate_certs: false
        status_code: 200
        follow_redirects: none
      register: rancher_api
      until: rancher_api.status == 200
      retries: 60
      delay: 10

    - name: Display Rancher API status
      ansible.builtin.debug:
        msg: "✓ Rancher API is responding (status: {{ rancher_api.status }})"

    - name: Verify Rancher is accessible via HTTPS
      ansible.builtin.uri:
        url: "https://localhost:8443"
        validate_certs: false
        status_code: [200, 301, 302]
      register: rancher_https

    - name: Display success message
      ansible.builtin.debug:
        msg:
          - "======================================================="
          - "✓ ALL TESTS PASSED!"
          - "✓ Docker installed and running"
          - "✓ Rancher container deployed and running"
          - "✓ Rancher API responding"
          - "✓ Rancher web interface accessible"
          - "======================================================="
