---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install Python dependencies for Docker
      ansible.builtin.package:
        name:
          - python3-pip
        state: present

    - name: Install Docker Python library
      ansible.builtin.pip:
        name:
          - docker>=5.0.0
        state: present
